#define BEAR_COUNT 1000
#define BEAR_PACE 20000

#define BEAR_HEIGHT 19
#define BEAR_LENGTH 51
#define BEAR_OFFSET 5

#define _1_BEAR_0 "       _                                        "
#define _1_BEAR_1 "      (\\\\  _                      ___           "
#define _1_BEAR_2 "     .-\"`\"(\\\\                _.\"\"`   `\"-.       "
#define _1_BEAR_3 "    /      ` `-._        _.-\"            `\\__   "
#define _1_BEAR_4 "   6   6)        `-.__.-'                    `\","
#define _1_BEAR_5 "  /                                         `;-`"
#define _1_BEAR_6 " /     ,                                     |  "
#define _1_BEAR_7 "()    /  /`                                  |  "
#define _1_BEAR_8 " `---`\"~``\\                                  |  "
#define _1_BEAR_9 "           \\                                 |  "
#define _1_BEAR_10 "            \\            \\      /           /   "
#define _1_BEAR_11 "            /`,   ,      |     |           /    "
#define _1_BEAR_12 "           /   \"-.|      |     |         /'     "
#define _1_BEAR_13 "          /     / |     /,__   |       /`\\      "
#define _1_BEAR_14 "         /    /'  |    /    `\"'\\      (   \\     "
#define _1_BEAR_15 "      __/   /'    |   |         `\\     \\   \\    "
#define _1_BEAR_16 "      \\    /      |   |           `\\    \\   \\   "
#define _1_BEAR_17 "       `-,/      /    |            /     |-\"`   "
#define _1_BEAR_18 "                `\"\"\"^^^           `^^\"\"\"\"`      "

#define _2_BEAR_0 "       _                                         " 
#define _2_BEAR_1 "      //)  _                      ___            " 
#define _2_BEAR_2 "     .-\"`\"//)                _.\"\"`   `\"-.        " 
#define _2_BEAR_3 "    /      ` `-._        _.-\"            `\\__ ,, " 
#define _2_BEAR_4 "   6   6)        `-.__.-'                      \" " 
#define _2_BEAR_5 "  /                                         `;'` " 
#define _2_BEAR_6 " /     ,                                     |   " 
#define _2_BEAR_7 "()    /  /`                                  |   " 
#define _2_BEAR_8 " `---`\"~``\\                                  |   " 
#define _2_BEAR_9 "           \\                                 |   " 
#define _2_BEAR_10 "            \\                               /    " 
#define _2_BEAR_11 "            \\                     /       /     " 
#define _2_BEAR_12 "            /                      |     /'      " 
#define _2_BEAR_13 "           /     /`.,.,..,__       \\     \\       " 
#define _2_BEAR_14 "          /    /`   |   |    `\"..,,,\\     \\      " 
#define _2_BEAR_15 "       __/   /`     |   |         |  \\     \\     " 
#define _2_BEAR_16 "       \\    /       |   |         |   \\     \\    " 
#define _2_BEAR_17 "        `-,/       /    |        /,.,-/,.,-\"`    " 
#define _2_BEAR_18 "                  `\"\"\"^^^                        " 
